<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-DJ4FDME" failures="9" tests="62" name="Test" time="15.606" errors="0" timestamp="2025-05-28T20:47:28 IST">
  <testcase classname="demoTestNG.FirstScenario" name="sixth_testcase" time="0.025"/>
  <testcase classname="demoTestNG.FirstScenario" name="fifth_testcase" time="0.003"/>
  <testcase classname="demoTestNG.FirstScenario" name="forth_testcase" time="0.003"/>
  <testcase classname="demoTestNG.FirstScenario" name="third_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario" name="first_testcase" time="0.006"/>
  <testcase classname="demoTestNG.FirstScenario" name="second_testcase" time="0.004"/>
  <testcase classname="demoTestNG.FirstScenario4" name="fifth_testcase" time="0.005"/>
  <testcase classname="demoTestNG.FirstScenario4" name="first_testcase" time="0.003"/>
  <testcase classname="demoTestNG.FirstScenario4" name="forth_testcase" time="0.016">
    <failure type="java.lang.AssertionError" message="expected [HelloWorld] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [HelloWorld] but found [Hello]
at demoTestNG.FirstScenario4.forth_testcase(FirstScenario4.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- forth_testcase -->
  <testcase classname="demoTestNG.FirstScenario4" name="second_testcase" time="0.005"/>
  <testcase classname="demoTestNG.FirstScenario4" name="sixth_testcase" time="0.004"/>
  <testcase classname="demoTestNG.FirstScenario4" name="third_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario5" name="fifth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario5" name="first_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario5" name="forth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario5" name="second_testcase" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello1] but found [Hello]
at demoTestNG.FirstScenario5.second_testcase(FirstScenario5.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- second_testcase -->
  <testcase classname="demoTestNG.FirstScenario5" name="sixth_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario5" name="third_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario2" name="fifth_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario2" name="first_testcase" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [HelloWorld] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [HelloWorld] but found [Hello]
at demoTestNG.FirstScenario2.first_testcase(FirstScenario2.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="demoTestNG.FirstScenario2" name="forth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario2" name="second_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario2" name="sixth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario2" name="third_testcase" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [HelloWorld] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [HelloWorld] but found [Hello]
at demoTestNG.FirstScenario2.third_testcase(FirstScenario2.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- third_testcase -->
  <testcase classname="demoTestNG.FirstScenario3" name="fifth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario3" name="first_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario3" name="forth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario3" name="second_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario3" name="sixth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario3" name="third_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario8" name="fifth_testcase" time="0.003"/>
  <testcase classname="demoTestNG.FirstScenario8" name="first_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario8" name="forth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario8" name="second_testcase" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [HelloWorld] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [HelloWorld] but found [Hello]
at demoTestNG.FirstScenario8.second_testcase(FirstScenario8.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- second_testcase -->
  <testcase classname="demoTestNG.FirstScenario8" name="sixth_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario8" name="third_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario9" name="fifth_testcase" time="0.003"/>
  <testcase classname="demoTestNG.FirstScenario9" name="first_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario9" name="forth_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario9" name="second_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario9" name="sixth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario9" name="third_testcase" time="0.003"/>
  <testcase classname="demoTestNG.FirstScenario6" name="fifth_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario6" name="first_testcase" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [HelloWorld] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [HelloWorld] but found [Hello]
at demoTestNG.FirstScenario6.first_testcase(FirstScenario6.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="demoTestNG.FirstScenario6" name="second_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario6" name="sixth_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario6" name="third_testcase" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demoTestNG.FirstScenario6.third_testcase(FirstScenario6.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- third_testcase -->
  <testcase classname="demoTestNG.FirstScenario6" name="forth_testcase" time="0.001">
    <skipped/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="demoTestNG.FirstScenario7" name="fifth_testcase" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello1] but found [Hello]
at demoTestNG.FirstScenario7.fifth_testcase(FirstScenario7.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="demoTestNG.FirstScenario7" name="first_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario7" name="forth_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario7" name="second_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario7" name="sixth_testcase" time="0.003"/>
  <testcase classname="demoTestNG.FirstScenario7" name="third_testcase" time="0.002"/>
  <testcase classname="org.xyz.automation.proj.FetchData" name="calendarfun" time="5.206">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://www.facebook.com] but found [https://www.facebook.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.facebook.com] but found [https://www.facebook.com/]
at org.xyz.automation.proj.FetchData.calendarfun(FetchData.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- calendarfun -->
  <testcase classname="org.xyz.automation.proj.FacebookPage" name="signup_func" time="4.382"/>
  <testcase classname="demoTestNG.FirstScenario10" name="fifth_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario10" name="first_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario10" name="forth_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario10" name="second_testcase" time="0.001"/>
  <testcase classname="demoTestNG.FirstScenario10" name="sixth_testcase" time="0.002"/>
  <testcase classname="demoTestNG.FirstScenario10" name="third_testcase" time="0.001"/>
  <testcase classname="org.xyz.automation.proj.FacebookPage" name="login_func" time="0.0">
    <ignored/>
  </testcase> <!-- login_func -->
  <testcase classname="org.xyz.automation.proj.FacebookPage" name="managebrowser" time="0.0">
    <ignored/>
  </testcase> <!-- managebrowser -->
</testsuite> <!-- Test -->
